<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.9.5
 */

/**
 * Database `parksmgmt_db`
 */

/* `parksmgmt_db`.`mfgs` */
function getMfgs()
{
    return array(
        array('id' => '1','name' => 'Federal Coach','db_name' => 'Federal','desc' => '<h2><img style="margin-bottom: 1.5em;" alt="" src="../images/federal-cb.jpg" width="790" height="407" /><br />FEDERAL COACH... INTELLIGENT BY DESIGN</h2>
<p>Federal Coach has deep roots in the specialty vehicles industry, and in fact can trace its roots back to the birthplace of the original six-door limousines. For more than one hundred years, Federal Coach and its forerunners have been leaders in specialty vehicle manufacturing focusing on Quality, Safety, Service and Value.<br /><br />Federal\'s commitment to quality is shared by every team members who interfaces with the customer, and those who build each Federal professional vehicle. From Design and Engineering, to Manufacturing and Office Administration, and Sales to Service, the people at Federal are always looking to improve its business and manufacturing processes.<br /><br />Federal Coach is a Ford Qualified Vehicle Modifier (QVM) and Cadillac Master Coachbuilder (CMC), having successfully completed assessments and site inspections on an ongoing basis made by both Lincoln/Ford and Cadillac/GM. Additionally, Federal Coach is committed to complying with all FMVSS and NHTSA safety requirements.<br /><br />You have a choice in the professional vehicles that you purchase, drive and operate on a daily basis. Your complete satisfaction is what\'s important to Federal team members. Service before-, during-, and after-the-sale will enable Federal to continuously earn your business.<br /><br />Combining attractive styling and reliable construction, with the most sought after features, Federal\'s funeral coaches, limousines and vans are some of the best selling models in America. In today\'s competitive market, value is paramount to any purchase decision. And, Federal Coach leads the market in offering funeral director and livery operators a complete line of dependable, cost-effective products providing a strong return on your investment.<br /><br />Parks Superior is your one stop source for access to this prestigious Coach Builder. Call Parks Today!</p>','url' => 'www.federalcoach.com','logo' => 'newfederal-logo.gif','index' => NULL,'created_at' => '2007-10-22 16:12:07','updated_at' => '2014-09-04 08:34:31'),
        array('id' => '2','name' => 'Superior Coach','db_name' => 'Superior','desc' => '<p><img style="margin-bottom: 1.5em;" alt="" src="../images/superior-cb.jpg" width="790" height="407" /><br />The roots of the Superior Coaches date back to 1915 when The Garford Motor Truck Company of Elyria, Ohio, transferred its production operations to Lima, Ohio. Garford, established in 1909, manufactured heavy trucks. In 1923, Garford introduced a special, 25-29 passenger bus chassis and a group of local, Lima businessmen formed the Superior Motor Coach Body Company to produce deluxe motor coach bodies for the locally built Garford bus chassis.</p>
<p>In 1925, The Superior Motor Coach Body Company introduced a line of hearse and ambulance bodies. These professional cars, built on the Studebaker chassis, were contemporary in appearance and constructed to high quality standards. Later in the early \'30s, after Studebaker had merged with Pierce-Arrow, Superior began producing a line of hearses on the Pierce Arrow chassis. By 1936, the company expanded its product offerings to include hearse models on a Pontiac chassis. The first Superior Cadillac coaches were produced in 1938.</p>
<p>The company\'s name was changed to The Superior Coach Corporation in 1940. And the years that followed saw hearses styled on Cadillac, LaSalle and Pontiac chassis. By 1949, the company had added Chrysler, DeSoto and Dodge chassis to its funeral coach line, offering customers a smaller investment and lower overhead.</p>
<p>The 1950s were a time of major styling changes, both inside the vehicles and out. Many models were offered at this time, as well. Major redesigns came in 1957, 1965, 1971 and 1977, the year professional vehicles were dramatically downsized. During that time span, the company had been purchased by Sheller-Globe Corporation which later sold its Superior Coach funeral-car business in 1981 to a group of private investors who re-named the Company Superior Coaches. Darrel Metzger, Superior\'s long-time funeral car and ambulance sales manager became president of the new operation which remained in Lima, Ohio.</p>
<p>In 1981, Superior Coaches acquired the Sayers &amp; Scovill funeral coach business, better known as The S&amp;S Coach Company. At that time, all S&amp;S Coach designs, dies, fixtures and manufacturing techniques were merged into the Lima operation and the Company name became S&amp;S/Superior of Ohio.</p>
<p>As sales grew, the company constructed a new 180,000 square foot Lima plant in 1995 which is where Superior Coaches funeral coaches and six-door limousines are built today on Cadillac and Lincoln chassis. In 1999, the Company acquired the Eureka Coach and Miller-Meteor funeral vehicle lines and the Company name was changed to Accubuilt in 2000. In 2005, the Company acquired the rights to produce LCW by Accubuilt six-door limousines.</p>
<p>With more than 80 years in the funeral coach business, Superior Coaches has made significant contributions to the advancement of the modern hearse. More Superior Coaches funeral vehicles are in service today than any other brand. Today, as we enter the third millennium, Superior Coaches is recognized as the leader in traditional styling in its design and manufacture of funeral coaches and limousines. The vehicles are still built in Lima, Ohio, but today under the Accubuilt, Inc. corporate umbrella. This state-of-the-art facility also manufactures quality professional vehicles for four other distinct brand names.</p>','url' => 'www.superiorcoaches.com/','logo' => 'accubuilt_superior_logo.jpg','index' => NULL,'created_at' => '2007-10-22 16:12:41','updated_at' => '2016-03-29 10:06:51'),
        array('id' => '3','name' => 'Eureka Coaches','db_name' => 'Eureka','desc' => '<img src="images/eureka-cb.jpg" alt="" />
<p>Eureka Coach\'s colorful corporate name extends far back in history to 1871 when in Rock Falls, Illinois,<br />the company was originally founded. It was not incorporated, however, for another 16 years (1887) which&nbsp;actually gives the Eureka Manufacturing Company the honor of celebrating not one, but two, birthdays.</p>
<p>Like many successful companies, Eureka Mfg. Co. originally made one product before later changing to&nbsp;another. Eureka\'s first products included desks, chairs and church furniture before switching over to&nbsp;horse-drawn vehicles, such as cars, wagons and buggies. Eventually, Eureka was among the largest<br />vehicle producers in the United States.</p>
<p>Times changed with the invention of the automobile, and again, Eureka began pursuing new avenues. With&nbsp;a large investment in woodworking equipment and a number of highly skilled woodworkers and craftsmen,&nbsp;Eureka turned to the manufacturing of beautifully carved wooden bodies for hearses and ambulances.</p>
<p>Eureka\'s first major innovation in its funeral car design came in the early 1920s, when the company&nbsp;pioneered its totally new style of funeral car - the limousine. Within a few years, all funeral car and ambulance&nbsp;manufacturers had followed Eureka\'s design and had changed exclusively to this attractive new style.</p>
<p>Eureka\'s next development was also a leader in the funeral industry. Eureka employee, Wilber Myers (who&nbsp;later became one of Eureka\'s company presidents) developed a movable casket table to ease the task of&nbsp;loading and unloading caskets.</p>
<p>Over the years, Eureka had developed a number of innovative creations for the industry and was faced with a&nbsp;growing list of competitors, making the struggle for their market share increasingly difficult from year to year.&nbsp;In 1964, faced with a hard decision, the Eureka Mfg. Co. closed its doors.</p>
<p>All was not lost, however. In 1980, Thomas McPherson was personally able to resurrect the proud Eureka&nbsp;name when he opened his own funeral coach manufacturing company in Toronto. Through the next several&nbsp;years, Eureka had rebounded to, once again, become a leading competitor in the industry.</p>
<p>In 1989, a group of investors (CCE, Inc.) moved the company to a brand new facility in Norwalk, Ohio. In 1993,&nbsp;looking to expand their market share and manufacturing efficiencies, the group purchased the Miller-Meteor&nbsp;name which also has a rich history in the professional vehicle industry. This operation ran for six years before&nbsp;being purchased by the largest producer of funeral vehicles.</p>
<p>In July 1999, Superior Holdings, Inc. (a PNC Company) acquired certain assets of CCE, Inc. and moved all&nbsp;manufacturing to their Lima, Ohio facility. Today, under the Accubuilt, Inc. corporate title, this facility&nbsp;manufactures quality professional vehicles for several distinct brand names including Eureka Coach.</p>
<p>With a team of quality builders, designers and engineers, Eureka continues its rich heritage of product&nbsp;innovations and customer satisfaction with "contemporary style." Eureka Coach builds its vehicles on the&nbsp;foundation of quality and craftsmanship and is recognized for its trend-setting designs and dignity it&nbsp;provides its customers. This is evident in the styles of yesteryear as well as those of today.<br /><br /></p>','url' => NULL,'logo' => 'eureka_logo.jpg','index' => NULL,'created_at' => '2007-10-22 16:13:09','updated_at' => '2014-01-10 10:28:51'),
        array('id' => '4','name' => 'Eagle Coach','db_name' => 'Eagle','desc' => '<p><img style="margin-bottom: 1.5em; display: block; margin-left: auto; margin-right: auto;" title="Eagle Coach" src="../images/neweagle.jpg" alt="Eagle Coach" width="750" height="386" /></p>
<p>From its humble beginnings in 1982, Eagle Coach Company has continuously strived to design and manufacture high quality professional vehicles that exceed customer expectations. Today, over thirty (30) years later, Eagle Coach Company is arguably the recognized industry leader in overall quality, style, innovation and customer satisfaction. In 2006, Eagle expanded its manufacturing facility in response to growing customer demand, and now also offers a complete line-up of six-door limousines, along with its other specialty vehicles. &nbsp;In 2011, Eagle was first to the market with the new Lincoln MKT coaches, and in 2013 is first to market the all-new Cadillac XTS coaches and limousines with fully-painted roofs and with an Urn Enclave in every coach. <br /><br />Eagle Coach Company is a customer-driven professional vehicle manufacturer that can trace its origins back to the 1940s and the armored car legend Hess &amp; Eisenhardt. When Hess &amp; Eisenhardt sold its Cincinnati funeral coach division in the early 1980&rsquo;s, Eagle Coach Company was established, retaining a team of talented and experienced employees. Since then, Eagle Coach Company has grown and has earned a reputation for building the highest quality, most tastefully styled professional cars in &nbsp;the industry. <br /><br /><strong><em>Expect Excellence</em> </strong>is more than a slogan; it&rsquo;s actually the driving force behind what has made Eagle successful. The funeral coaches, six-door limousines and other specialty vehicles used by funeral directors create a lasting impression on the families they serve. Eagle Coach Company is dedicated to producing the highest quality professional vehicles that reflect positively on the funeral homes that use them. <br /><br />When you purchase an Eagle professional vehicle... Expect excellence.</p>','url' => 'www.eaglecoachcompany.com','logo' => 'eagle_logo.jpg','index' => NULL,'created_at' => '2007-10-22 16:13:25','updated_at' => '2014-05-15 16:36:19'),
        array('id' => '5','name' => 'S&S Coach','db_name' => 'S&S','desc' => '<p><img style="margin-bottom: 1.5em;" src="../images/sscoach.jpg" alt="" width="795" height="407" />One hundred and thirty years is a long time to be in business. And it\'s particularly notable if the company in question manufactures the oldest brand in a highly competitive and specialized field. This longevity takes on added distinction when that company has also been the industry leader for the greater part of its existence. Such is the honor of The S&amp;S Coach Company.<br /><br />S&amp;S was founded in 1876 as the Sayers and Scovill Company by William Sayers and A. R. Scovill. The funeral coach business was thriving at the turn of the 20th century, and sharp competition helped create the superlative standards of craftsmanship and design which remain an S&amp;S tradition to this day.</p>
<p>By 1906, the internal combustion engine was revolutionizing the funeral carriage trade. Unsurpassed quality and engineering ingenuity enabled S&amp;S to be the only firm to accomplish the motor car changeover and continuously maintain its position in the marketplace. Today, The S&amp;S Coach Company is the only true survivor of the pre-automotive funeral coach era, still in continuous operation.</p>
<p>The succeeding years saw the design of the professional car assume various appearances -- from ornate, lavishly-carved body panels to towncar and limousine concepts -- and all along the way, the S&amp;S nameplate denoted leadership in quality, innovation and refinement.</p>
<p>Today, over 130 years later, The S&amp;S Coach Company is still recognized as the leader in professional car excellence.</p>','url' => 'www.sscoachcompany.com','logo' => 'accubuilt_sns.jpg','index' => NULL,'created_at' => '2008-03-25 11:09:26','updated_at' => '2017-08-30 11:12:24'),
        array('id' => '6','name' => 'MK Coach','db_name' => 'MK','desc' => '<p><img style="margin-bottom: 1.5em;" alt="" src="../images/mk-cb.jpg" width="790" height="407" /></p>
<p>The newest member of our Coachbuilder family is MK Coach. &nbsp;Their mission is "To Deliver a Traditional, Beautiful, Affordable, and a Dependable Funeral Coach for a price that makes sense to today\'s Funeral Directors." &nbsp;This new line is priced at a little over half of the cost of today\'s Funeral Coaches, but compromises nothing! &nbsp;It\'s styling is Traditional and Beautiful inside and out.</p>
<p>The MK Story:</p>
<p>MK Coach Company is owned by Mike Kellerman and Family. The Kellerman family has been serving the Funeral Industry for over 30 years by manufacturing high quality funeral coaches built on a Cadillac, Lincoln, Chrysler, Chevrolet, and Buick chassis.</p>
<p>I sold our funeral coach manufacturing operation in 2006 but have kept a close eye on the funeral industry. We have seen many changes in funeral service since 2006 in part due to the economy and cremation. When an industry experiences such changes as we are seeing within the funeral industry today the suppliers need also change their products to meet the new needs of today&rsquo;s Funeral Director.</p>
<p>The MK 300 was developed in part because many Funeral Coach Dealers and Funeral Directors have asked for a Funeral Coach that is traditional in its styling, but priced to make sense for today&rsquo;s Funeral Director. The MK 300 is priced at a little over half the cost of today&rsquo;s Funeral Coaches, but you compromise nothing! Its styling is Traditional and Beautiful inside and out. It carries a full size casket and air tray. Our Coach carries a full factory warranty, along with our company conversion warranty, that matches in length of time the OEM factory warranty. A very important issue to keep in mind when purchasing a new coach, is how it is built. After 30 years building funeral coaches, I am very sure of one thing, the best engineers in designing and building a funeral coach are the OEM factory engineers. Today&rsquo;s cars are almost trouble free for over 100,000 miles. It was my goal in designing the MK 300, to change or alter as little as possible on the original chassis. I did not want to cut the chassis in two; this would lead to cutting the brake lines, gas lines, electrical harness, frame or uni-body, and we would need to design and manufacture new side doors along with many other parts. I am very pleased to state that the MK 300 is built on a heavy duty chassis that was designed for 7 passengers, plus cargo. This is more than enough capacity to carry the driver, passenger, and casket. We do NOT cut the frame, brake lines, gas lines, and electrical harness in hope to deliver to our customer the most dependable, trouble free coach on the market. I am very confident we do!</p>','url' => 'www.mkcoaches.com','logo' => 'mk_coach_shield.jpg','index' => NULL,'created_at' => '2013-09-11 10:54:25','updated_at' => '2014-09-04 08:34:49'),
        array('id' => '7','name' => 'New England Coach','db_name' => 'N.E. Coach','desc' => '<div class="gallery_header">
<h1>First Call Vehicles&nbsp;</h1>
</div>
<div>
<div class="galleree">
<div>The most&nbsp;versatile&nbsp;vehicle in your fleet, based off of a pre-owned vehicle to fit any budget. We take a (1) one year old Town &amp; Country "Touring Package" chassis and convert it into a First Call Vehicle. It is the most versatile vehicle in the funeral industry. You can use it as a:</div>
<div>
<ul>
<li>Hearse</li>
<li>Removal Vehicle</li>
<li>Transport Vehicle</li>
<li>Flower Car</li>
<li>Service Vehicle</li>
</ul>
</div>
<div>Removable side panels with chrome bows can be instantly removed so you can enter a nursing home or neighborhood unannounced.&nbsp;The casket floor folds in half exposing two "Stow &amp; Go" Seats, so you can instantly use this vehicle to transport four people. The floor is also completely removable exposing the rear seat making it a full seven passenger vehicle.</div>
<div>&nbsp;</div>
<div>Please look through the pictures and call us with any questions.</div>
</div>
</div>','url' => NULL,'logo' => 'ne_coach_logo.png','index' => NULL,'created_at' => '2014-01-13 12:24:57','updated_at' => '2014-01-13 12:24:57'),
        array('id' => '8','name' => 'Platinum Coach','db_name' => 'Platinum','desc' => '<p>Platinum Funeral Coach may be a new name to the industry, but our experience started in 1985. Joe Kellerman, the CEO of Platinum, was just 14 years old when he started washing and detailing hearses for his uncle Mike Kellerman. Our company is centered on one main principal, a principal Joe learned from his uncle: the value of family. Joe decided to carry on that same idea in his own business: the majority of our employees are family members, and the other half we consider family.</p>
<p>At Platinum Funeral Coach, we do things differently- not only do we care about quality--we deliver quality. We strive to build a product we are truly proud of, one that is a tool and aide to those who use it.</p>
<p>At Platinum Funeral Coach, we do things our way &hellip; the Kellerman way &hellip; where excellence is the goal and family is the inspiration.</p>
<p>&nbsp;</p>','url' => 'www.platinumfuneralcoach.com','logo' => 'platinumlogoshieldonly.jpg','index' => NULL,'created_at' => '2014-04-09 15:56:18','updated_at' => '2014-09-04 08:43:18'),
        array('id' => '9','name' => 'K2 Products','db_name' => 'K2 Products','desc' => '<p id="u1300-4"><span id="u1300">K2 First Call Vehicles</span><span id="u1300-2">&nbsp;</span><span id="u1300-3">is a company fueled by the passion to create and build versatile and lasting products for the funeral director. They strive to build a relationship with their clients by providing them versatile, lasting products. Their hope is that their character comes through with every experience you have.</span></p>
<p>It has been said that the culmination of ones past experiences shape and define their future. That is certainly the case for Steve Kellerman, who owns K2 Products with his wife Rachel. Not only is Steve the owner of K2 Products, but also the sales manager for his brother Joe Kellerman&rsquo;s company Platinum Funeral Coach.</p>
<p id="u1279-14">"We believe that a product can be made based on quality and detail, rather than numbers and volume. We will bring the family relationship back into this industry.&rdquo; ~Steve Kellerman</p>','url' => 'www.k2products.com','logo' => 'threeshields.jpg','index' => NULL,'created_at' => '2014-06-26 10:47:40','updated_at' => '2014-06-26 11:03:25'),
        array('id' => '10','name' => 'BINZ','db_name' => 'BINZ','desc' => NULL,'url' => 'www.binz.com/en/hearses/metatron.html','logo' => 'binz.png','index' => NULL,'created_at' => '2014-06-03 13:47:27','updated_at' => '2014-09-04 08:43:55'),
        array('id' => '11','name' => 'DaBryan','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2014-08-13 13:37:38','updated_at' => '2016-10-25 10:22:07'),
        array('id' => '12','name' => 'LCW','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2014-08-18 10:07:56','updated_at' => '2014-08-18 10:07:56'),
        array('id' => '13','name' => 'Krystal Coach','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2014-08-18 11:38:41','updated_at' => '2014-08-18 11:38:46'),
        array('id' => '14','name' => 'Miller Meteor','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2014-08-19 09:23:22','updated_at' => '2014-08-19 09:23:26'),
        array('id' => '15','name' => 'Henry Brothers','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2014-09-03 09:43:57','updated_at' => '2014-09-03 09:44:00'),
        array('id' => '16','name' => 'Royale','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2014-11-13 09:44:37','updated_at' => '2014-11-13 09:44:37'),
        array('id' => '17','name' => 'Armbruster Stageway','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2015-02-11 12:47:09','updated_at' => '2015-02-11 12:47:14'),
        array('id' => '18','name' => 'Lima Commercial Coach','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2015-04-10 13:00:16','updated_at' => '2015-04-10 13:00:22'),
        array('id' => '19','name' => 'Lehmann-Peterson','db_name' => NULL,'desc' => NULL,'url' => 'www.lehmann-peterson.com','logo' => NULL,'index' => NULL,'created_at' => '2016-11-01 16:23:06','updated_at' => '2016-11-01 16:23:06'),
        array('id' => '20','name' => 'Parks Superior Sales','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2017-07-10 07:18:11','updated_at' => '2017-07-10 07:18:13'),
        array('id' => '21','name' => 'Hess & Eisenhardt','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2017-09-11 09:54:56','updated_at' => '2017-09-11 09:54:56'),
        array('id' => '22','name' => 'Precision Coach','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2019-05-21 09:37:21','updated_at' => '2019-05-21 09:38:06'),
        array('id' => '23','name' => 'Prestige Coach','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2019-06-12 12:50:41','updated_at' => '2019-06-12 12:50:41'),
        array('id' => '24','name' => 'Bennett Funeral Coaches','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2019-12-04 09:08:12','updated_at' => '2019-12-04 09:09:29'),
        array('id' => '25','name' => 'Tom Caserta','db_name' => NULL,'desc' => NULL,'url' => NULL,'logo' => NULL,'index' => NULL,'created_at' => '2020-07-29 08:39:23','updated_at' => '2020-07-29 08:39:23')
    );
}

// SELECT `old_key`, `new_key` FROM `_ids` WHERE `new_table` LIKE 'mfgs'
const MFG_KEYS = [
    'cqkczp5i' => 1,
    'cp63gv6v' => 2,
    '28h5f327' => 3,
    'tyheal49' => 4,
    '9j7x6r7m' => 5,
    'udyhsqos' => 6,
    'qczy2ew9' => 7,
    'x7rgzfj4' => 8,
    'a1gmeggg' => 9,
    '9p46w82p' => 10,
    'CD9GD4N8' => 11,
    'NEDYDH33' => 12,
    '1E19HU6E' => 13,
    'EK0W4AOX' => 14,
    'UF2YZYE2' => 15,
    'OYTS54CT' => 16,
    'FR80WNAQ' => 17,
    '6T0VM4AY' => 18,
    'VYQKFK2N' => 19,
    'ABVKG003' => 20,
    'JJL47NBE' => 21,
    'LFO1AECR' => 22,
    '1Z086L6I' => 23,
    'R58XENW6' => 24,
    'VR7UNKSE' => 25,
];
